### ISSUE TITLE
Getting a lot of flicker when Sponza scene is added

### ISSUE THREAD

**Issue by mmmovania** [LDeakin/VkVolume#1]
Thanks for sharing your code. I managed to compile it on Windows 8.1 x64 on VS2019 successfully. When I enable sponza along with volume, the sponza rendering flickers like this
![image](https://user-images.githubusercontent.com/1354859/145221529-d33d22f3-bc33-48cc-af3c-c8af9224d555.png)
You can see the floor and the entire sponza mesh flickers as if in a disco. It appears to be something related to sync issue between rendering and display. Any ideas on how to fix it?

**Comment by LDeakin** [comment]
I'm not sure exactly what is causing this green floor/flickering issue, I wasn't able to reproduce it.
Since the rendering of the Sponza scene is pretty much handled by Vulkan-samples, I've updated the repository to utilise the latest Vulkan-samples (and no longer my fork).
Could you see if the issue persists with the latest version?

**Comment by mmmovania** [comment]
Yes the issue persists with the latest vulkan-samples.

**Comment by mmmovania** [comment]
Just sharing with you. I have managed to port the distance map calculation from vulkan to opengl v 4.6 using glfw. My total C code so far for distance map calc is approx 300 lines. Vulkan is a bit too verbose but it sure does have its use case when you want to get total control. But for me who likes to experiment quickly opengl is simpler to test out.
